[package]
name = "wayland6502"
version = "0.1.0"
authors = ["Marcus Pinnecke <marcus.pinnecke@elinvar.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
